### PR TITLE
fix(type): add FilterOperator enum

### PR DESCRIPTION
**Pull request by JustinMartinDev**
### General

Proposal based on [filter-parser](https://github.com/ForestAdmin/forest-express-sequelize/blob/b99f5e77e02acb96a9d46503f5fb907a6ab46d1a/src/services/filters-parser.js#L56) and [filter-date-parser](https://github.com/ForestAdmin/forest-express/blob/main/src/services/base-operator-date-parser.js)

- [x] Write an explicit title for the Pull Request, following [Conventional Commits specification](https://www.conventionalcommits.org)
- [x] Test manually the implemented changes
- [x] Validate the code quality (indentation, syntax, style, simplicity, readability)
- [x] Ensure that Types have been updated according to your changes (if needed)

### Security

- [x] Consider the security impact of the changes made

### CODE REVIEW

**Comment by JustinMartinDev** [comment]
News @jeffladiray ?

**Comment by jeffladiray** [comment]
Yes, sorry for the delayed response.
It seems like you are missing quite a few operators, especially the one related to Date filtering (The complete list of operators supported is available [here](https://github.com/ForestAdmin/agent-nodejs/blob/fe0cce6/packages/datasource-toolkit/src/interfaces/query/condition-tree/nodes/operators.ts#L63) (On our new agent).

If you feel like updating this contribution with these, I'll happily merge it.
Otherwise, I can file a ticket on our end.

**Comment by JustinMartinDev** [comment]
I amend my previous commit to include operator of this fie https://github.com/ForestAdmin/forest-express/blob/main/src/services/base-operator-date-parser.js

**Review by jeffladiray — APPROVED** [review]

**Comment by jeffladiray** [comment]
Thanks you for this contribution 🙌

**Pull request merged**
